src/main/java/com/objects/marketbridge/domain/Delivery.java

#5 feat : Delivery 연관관계 매핑

---

src/main/java/com/objects/marketbridge/domain/user/repository/UserCustomRepository.java
src/main/java/com/objects/marketbridge/domain/user/repository/UserJpaRepository.java
src/main/java/com/objects/marketbridge/domain/user/repository/UserRepository.java
src/main/java/com/objects/marketbridge/domain/user/service/UserService.java

기본적인 인터페이스 구조를 만들어두고 이메일 중복체크 러프하게 작성하였습니다.

[ :sparkles: |  |feature] 유저기본 인터페이스와 이메일 중복체크

---

src/main/java/com/objects/marketbridge/domain/user/dummy.java

git fork push 테스트

---

src/main/resources/schema-mysql.sql

- prod_order_detail 에 payment_key 컬럼 추가

[ :wrench: | #27 | fix ]  .sql 파일 수정

---

src/main/java/com/objects/marketbridge/domain/product/service/ProductService.java
src/main/resources/data-mysql.sql

- hour -> hours
- NullPointerException 제거

[ :white_check_mark: | #27 | fix ]  긴급 수정

---

src/main/java/com/objects/marketbridge/domain/member/controller/MemberController.java
src/main/java/com/objects/marketbridge/global/security/jwt/JwtTokenProvider.java
src/test/java/com/objects/marketbridge/domain/member/controller/MemberControllerTest.java
src/test/java/com/objects/marketbridge/domain/member/controller/integration/MemberControllerTest.java
src/test/java/com/objects/marketbridge/global/security/SpringSecurityTestConfig.java
src/test/java/com/objects/marketbridge/global/security/annotation/WithMockCustomUser.java
src/test/java/com/objects/marketbridge/global/security/annotation/WithMockCustomUserSecurityContextFactory.java

:recycle: #110 | spring security test 환경 설정 완료

---

src/main/java/com/objects/marketbridge/common/config/KakaoPayConfig.java
src/main/java/com/objects/marketbridge/common/domain/Membership.java
src/main/java/com/objects/marketbridge/common/domain/MembershipType.java
src/main/java/com/objects/marketbridge/common/dto/KakaoPayApproveResponse.java
src/main/java/com/objects/marketbridge/common/dto/KakaoPaySubsApproveRequest.java
src/main/java/com/objects/marketbridge/common/dto/KakaoPaySubsApproveResponse.java
src/main/java/com/objects/marketbridge/common/infra/KakaoPayService.java
src/main/java/com/objects/marketbridge/member/controller/MemberController.java
src/main/java/com/objects/marketbridge/member/controller/request/CreateSubsRequest.java
src/main/java/com/objects/marketbridge/member/dto/CreateSubsDto.java
src/main/java/com/objects/marketbridge/member/dto/SignUpDto.java
src/main/java/com/objects/marketbridge/member/infra/MembershipJpaRepository.java
src/main/java/com/objects/marketbridge/member/infra/MembershipRepositoryImpl.java
src/main/java/com/objects/marketbridge/member/service/MemberService.java
src/main/java/com/objects/marketbridge/member/service/port/MembershipRepository.java
src/main/java/com/objects/marketbridge/order/controller/OrderCancelReturnController.java
src/main/java/com/objects/marketbridge/order/service/dto/CancelRefundInfoResponseDto.java
src/main/java/com/objects/marketbridge/order/service/dto/ReturnRefundInfoResponseDto.java
src/main/resources/schema-mysql.sql
src/test/resources/schema-h2.sql

깃 머지 충돌 해결 

---

src/main/java/com/objects/marketbridge/common/config/KakaoPayConfig.java
src/main/java/com/objects/marketbridge/common/dto/KakaoPayReadyResponse.java
src/main/java/com/objects/marketbridge/common/infra/KakaoPayService.java

[ :sparkles: | | feature ] 카카오페이 수정

---

src/main/java/com/objects/marketbridge/common/domain/Membership.java
src/main/java/com/objects/marketbridge/common/dto/KakaoPayApproveRequest.java
src/main/java/com/objects/marketbridge/common/dto/KakaoPayApproveResponse.java
src/main/java/com/objects/marketbridge/common/dto/KakaoPayOrderResponse.java
src/main/java/com/objects/marketbridge/common/dto/KakaoPaySubsApproveRequest.java
src/main/java/com/objects/marketbridge/common/infra/KakaoPayService.java
src/main/java/com/objects/marketbridge/member/controller/MemberShipController.java
src/main/java/com/objects/marketbridge/member/infra/MembershipRepositoryImpl.java
src/main/java/com/objects/marketbridge/member/service/MemberShipService.java
src/main/java/com/objects/marketbridge/member/service/port/MembershipRepository.java
src/main/java/com/objects/marketbridge/payment/domain/Amount.java
src/main/java/com/objects/marketbridge/payment/domain/CardInfo.java
src/main/java/com/objects/marketbridge/payment/domain/PaymentActionDetail.java
src/main/resources/schema-mysql.sql
src/test/resources/schema-h2.sql

[ :sparkles: | | feature ] 카카오페이 정기결제 테스트 완료

---

src/docs/asciidoc/api/member/kakaoPaySubsApproved.adoc
src/docs/asciidoc/api/member/kakaoPaySubsReady.adoc
src/docs/asciidoc/api/member/kakaoPaySubsSubscribtion.adoc
src/docs/asciidoc/index.adoc
src/main/java/com/objects/marketbridge/member/controller/MemberShipController.java
src/test/java/com/objects/marketbridge/member/controller/MembershipControllerTest.java

멤버십 컨트롤러 테스트 코드 작성완료
멤버십 컨트롤러 RestDocs 작성완료

Issue#addresss

---

src/main/resources/application.yml

[ :recycle:| | refactor ] yml 수정

---

src/main/java/com/objects/marketbridge/common/dto/KakaoPayCancelRequest.java
src/main/java/com/objects/marketbridge/common/infra/KakaoPayService.java
src/main/java/com/objects/marketbridge/order/controller/OrderCancelController.java
src/main/java/com/objects/marketbridge/order/service/OrderCancelReturnService.java
src/main/java/com/objects/marketbridge/payment/infra/PaymentClientImpl.java

-  KakaoPayCancelRequest : getter, 기본생성자 추가

[ 🔧| | fix ] 카카오페이 주문 취소 에러 수정 

---

.gitignore

- /src/main/resources/logs/ 경로 추가

[ :recycle:| #419 | refactor ] 깃 이그노어 수정

---

src/main/java/com/objects/marketbridge/domains/coupon/infra/MemberCouponRepositoryImpl.java
src/main/java/com/objects/marketbridge/domains/coupon/service/port/MemberCouponRepository.java
src/test/java/com/objects/marketbridge/cart/service/GetCartListServiceTest.java
src/test/java/com/objects/marketbridge/order/mock/FakeMemberCouponRepository.java

GetCartListServiceTest 실패Test코드 주석 처리

[ :wrench: | | fix ] 실패Test코드 주석 처리 GetCartListServiceTest.java

---

Dockerfile

- logs 로 변경
- dockerfile WORDIR /app/logs 삭제

[ :wrench:|  | fix ] 로그파일 저장 경로

---

src/main/java/com/objects/marketbridge/domains/member/service/MemberService.java

[원인]
- MemberService 클래스에 @Transactrional(readonly = true) 가 걸려있어서 쓰기 작업이 안 되었음
[해결]
- 쓰기작업 하는 메서드에 @Transactrional 따로 추가해줌

[ :wrench:|  | fix ] MemberService  오류 수정

---

src/main/java/com/objects/marketbridge/common/exception/exceptions/ErrorCode.java
src/main/java/com/objects/marketbridge/domains/member/constant/MemberConst.java
src/main/java/com/objects/marketbridge/domains/member/controller/MemberController.java
src/main/java/com/objects/marketbridge/domains/member/controller/MemberShipController.java
src/main/java/com/objects/marketbridge/domains/member/domain/Address.java
src/main/java/com/objects/marketbridge/domains/member/dto/UpdateAddressRequestDto.java
src/main/java/com/objects/marketbridge/domains/member/service/MemberService.java
src/main/java/com/objects/marketbridge/domains/order/infra/address/AddressJpaRepository.java
src/main/java/com/objects/marketbridge/domains/order/infra/address/AddressRepositoryImpl.java
src/main/java/com/objects/marketbridge/domains/order/service/port/AddressRepository.java
src/main/resources/application.yml
src/test/java/com/objects/marketbridge/domains/member/controller/MemberControllerTest.java
src/test/java/com/objects/marketbridge/domains/member/controller/MembershipControllerTest.java

Issue#likes

---

src/docs/asciidoc/api/member/address/deleteAddress.adoc

deleteAddress.adoc의 제목 수정에서 삭제로 수정

[ :wrench: | | fix ] Address 스니펫 수정

---

src/main/resources/application.yml

[ :recycle:| #544 | refactor ]

---

src/main/java/com/objects/marketbridge/domains/cart/domain/Cart.java
src/test/java/com/objects/marketbridge/domains/cart/domain/CartTest.java

수량 수정 메서드 updateQuantity() 테스트 코드 추가

[ :white_check_mark:|  | test ] 장바구니 테스트 코드 추가

---

src/main/java/com/objects/marketbridge/domains/order/infra/order/OrderQueryRepositoryImpl.java

[ :recycle:|  | refactor ] OrderQueryRepositoryImpl 의 switch 문 제거

---

src/main/resources/application.yml

- 우선 로그의 시간대부터 KST로 고치고자 application.yml 을 수정하였다

[ :recycle: | #592 | fix] 타임존 에러 고치기(로그) - 2차시도

---

src/main/java/com/objects/marketbridge/common/logging/LoggingFilter.java

- LoggingFilter 화이트리스트에 docs 추가

[ :white_check_mark: | #544 | refactor] docs 요청할 때마다 로그남는문제 해결
